### ISSUE TITLE
XSS Still Possible via tags within tags?

### ISSUE THREAD

**Issue by arcreative** [flavorjones/loofah-activerecord#11]
Apologies if this isn't a loofah issue as much as a nokogiri one, but we had a penetration testing firm uncover what still seems like an XSS vulnerability. Saving a model with the following string:

```
Incoming evil content: <<b>img src=x onerror=alert('asdf')/>
```

`xss_foliate`s to

```
Incoming evil content: <img src=x onerror=alert('asdf')/>
```

Saving that content again correctly removes the image tag:

```
Incoming evil content: 
```

Not sure where this is being dropped, but seems like maybe as a stopgap, this should be run iteratively until the content stops changing or something?

**Comment by flavorjones** [comment]
Hi, @arcreative, thanks for reporting this. I'll take a look.

**Comment by flavorjones** [comment]
@arcreative Thanks for your patience. I've tried to reproduce what you're seeing, and cannot. If the string `<<b>img src=x onerror=alert('asdf')/>` is handled by Loofah::XssFoliate, then the resulting string will be `&lt;img src=x onerror=alert('asdf')/&gt;`.

Here's my attempt at reproducing what you're seeing:

```ruby
#! /usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord"
  gem "sqlite3"
  gem "loofah-activerecord"
end

require "active_record"
require "loofah/activerecord/xss_foliate"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content
  end
end

class Post < ActiveRecord::Base
  # xss_foliate
end

class BugTest < Minitest::Test
  def test_xss_foliate
    assert(Post.xss_foliated?)

    evil_string = "<<b>img src=x onerror=alert('asdf')/>"

    post = Post.create!(content: evil_string)
    assert_equal("&lt;img src=x onerror=alert('asdf')/&gt;", post.content)
  end
end
```

I think it's likely that your pen testing firm is looking at rendered HTML and seeing `<` and `>` when the actual string is `&lt;` and `&gt;`. Can you double-check on that and let me know? Or, if you can update the test case to demonstrate what you're seeing, that would be very valuable. Thanks!

**Comment by flavorjones** [comment]
Hi, @arcreative, when you have a moment can you please confirm my understanding as stated above, which is that this is not an XSS vector.

**Comment by flavorjones** [comment]
I'm going to close this, but if you find my analysis to be incorrect or based on wrong assumptions, and you believe that there is a true XSS vector here, please comment and we'll pick the conversation back up.

**Comment by arcreative** [comment]
@flavorjones Sorry, was traveling this week and unable to respond.  In the model, we're using `xss_foliate encode_special_chars: false`, as we still need to allow HTML, just not _bad_ html.  Updating your test with this option, I get the following:

```
Finished in 0.032403s, 30.8613 runs/s, 61.7227 assertions/s.

  1) Failure:
BugTest#test_xss_foliate [xss_foliate_test.rb:42]:
--- expected
+++ actual
@@ -1 +1 @@
-"&lt;img src=x onerror=alert('asdf')/&gt;"
+"<img src=x onerror=alert('asdf')/>"


1 runs, 2 assertions, 1 failures, 0 errors, 0 skips
```

I see after digging into the library that there's some documentation that it's not safe for HTML contexts, but what's the solution if we still need to allow HTML, but just want to sanitize that HTML?

**Comment by flavorjones** [comment]
It sounds like you want to use Loofah's `:strip` scrubber to remove only unsafe tags.

```ruby
#! /usr/bin/env ruby

require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  # Activate the gem you are reporting the issue against.
  gem "activerecord"
  gem "sqlite3"
  gem "loofah-activerecord"
end

require "active_record"
require "loofah/activerecord/xss_foliate"
require "minitest/autorun"
require "logger"

# This connection will do for database-independent bug reports.
ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  create_table :posts, force: true do |t|
    t.string :content
  end
end

class Post < ActiveRecord::Base
end

class PostDefault < Post
  xss_foliate
end

class PostStrip < Post
  xss_foliate strip: :content
end

class BugTest < Minitest::Test
  def setup
    super
    @evil_string = "<<b>img src=x onerror=alert('asdf')/>"
    @benign_string = "<b>hello</b>"
  end

  def test_setup
    refute(Post.xss_foliated?)
    assert(PostDefault.xss_foliated?)
    assert(PostStrip.xss_foliated?)
  end

  def test_default_xss_foliate_evil
    post = PostDefault.create!(content: @evil_string)
    assert_equal("&lt;img src=x onerror=alert('asdf')/&gt;", post.content)
  end

  def test_strip_xss_foliate_evil
    post = PostStrip.create!(content: @evil_string)
    assert_equal("&lt;<b>img src=x onerror=alert('asdf')/&gt;</b>", post.content)
  end

  def test_default_xss_foliate_benign
    post = PostDefault.create!(content: @benign_string)
    assert_equal("hello", post.content)
  end

  def test_strip_xss_foliate_benign
    post = PostStrip.create!(content: @benign_string)
    assert_equal("<b>hello</b>", post.content)
  end
end
```

Specifically you probably want `xss_foliate :strip => [:content]` or a similar variation.

**Comment by arcreative** [comment]
@flavorjones Thanks a bunch for your time on this, will try that out!
