### ISSUE TITLE
Does this support for Rails 5?

### ISSUE THREAD

**Issue by milind-patel** [flavorjones/loofah-activerecord#5]
# May i know is this gem supports in rails 5?

If no, is there any other gems available which are having same functionality as this gems and support for rails 5 ?

I need to truncate or strip unsafe tags using **xss_foliate**  before saving it to database .

**Comment by mnoack** [comment]
I had rails5 support (at least getting it to compile and pass tests) in a local commit, so I've made a pull request https://github.com/flavorjones/loofah-activerecord/pull/6

Hopefully @flavorjones can review and merge or ask for any changes to be made and get it in.

**Comment by milind-patel** [comment]
Thank you @mnoack :+1: 

It would be nice to have rails 5 support for loofah-activerecord. 

@flavorjones : Please review and merge code from @mnoack.

**Comment by flavorjones** [comment]
Released v2.0.0 with rails 5 support.
